# Generated by Django 4.2.7 on 2023-11-02 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Click', 'Click'), ('Payme', 'Payme'), ('Office', 'Office')], max_length=50)),
                ('reciever', models.CharField(blank=True, max_length=30)),
                ('completed', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.drivers')),
            ],
        ),
    ]
