# Generated by Django 4.2.7 on 2023-12-22 23:49

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0017_delete_driver2'),
        ('drivers', '0016_carcategory_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('total_bonus', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Operators',
            },
            bases=('user.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.PositiveIntegerField(default=0)),
                ('baggage', models.BooleanField(default=False)),
                ('for_women', models.BooleanField(default=False)),
                ('is_comfort', models.BooleanField(default=False)),
                ('client_phone', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('name_startin_place', models.CharField(blank=True, max_length=255, null=True)),
                ('starting_point_long', models.CharField(max_length=50)),
                ('starting_point_lat', models.CharField(max_length=50)),
                ('order_status', models.CharField(max_length=50)),
                ('destination_name', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_long', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_lat', models.CharField(blank=True, max_length=50, null=True)),
                ('grading_point', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('waiting_seconds', models.PositiveSmallIntegerField(default=0)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operators.client')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.drivers')),
            ],
        ),
        migrations.CreateModel(
            name='DriverPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_payments', to='drivers.drivers')),
            ],
        ),
    ]
