# Generated by Django 4.2.7 on 2023-11-13 16:02

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_delete_driver2'),
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('gender', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Operators',
            },
            bases=('user.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
