# Generated by Django 4.2.7 on 2023-12-22 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverpayment',
            name='status',
            field=models.CharField(blank=True, choices=[('otkazildi', 'otkazildi'), ('yechib_olindi', 'yechib_olindi')], max_length=50, null=True),
        ),
    ]
