# Generated by Django 4.2.7 on 2023-11-22 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_remove_order_active_remove_order_cancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='is_comfort',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='name_startin_place',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
