# Generated by Django 4.2.7 on 2023-11-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0004_order_client_phone_order_is_comfort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name_startin_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
