# Generated by Django 4.2.7 on 2023-11-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0005_alter_order_name_startin_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_phone',
            field=models.CharField(max_length=50),
        ),
    ]
