# Generated by Django 4.2.7 on 2023-11-22 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0006_alter_order_client_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client_phone',
            new_name='cl_phone',
        ),
    ]
