# Generated by Django 4.2.7 on 2023-11-22 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0007_rename_client_phone_order_cl_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cl_phone',
        ),
        migrations.AddField(
            model_name='order',
            name='client_phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
