# Generated by Django 4.2.7 on 2023-11-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0008_remove_order_cl_phone_order_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='client_phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination_lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination_long',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
