# Generated by Django 4.2.6 on 2023-11-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0009_alter_order_client_phone_alter_order_destination_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destination_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
