# Generated by Django 4.2.7 on 2023-11-02 21:23

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0016_alter_driver2_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('minimum', models.PositiveIntegerField()),
                ('waiting_cost', models.PositiveIntegerField()),
                ('bonus_percent', models.PositiveIntegerField()),
                ('baggage_cost', models.PositiveIntegerField()),
                ('sum_for_per_km', models.PositiveIntegerField(default=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fullname', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('car_type', models.CharField(max_length=30)),
                ('car_number', models.CharField(max_length=10)),
                ('sms_code', models.CharField(max_length=30)),
                ('sms_code_sent_date', models.DateTimeField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('gender', models.CharField(max_length=15)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('has_baggage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.carcategory')),
            ],
            options={
                'verbose_name': 'Drivers',
            },
            bases=('user.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
