# Generated by Django 4.2.6 on 2023-10-12 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarType',
            new_name='CarCategory',
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=15)),
                ('car_type', models.CharField(max_length=30)),
                ('car_number', models.CharField(max_length=10)),
                ('sms_code', models.CharField(max_length=30)),
                ('confirmed', models.BooleanField(default=False)),
                ('gender', models.CharField(max_length=15)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('has_baggage', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.carcategory')),
            ],
        ),
    ]
