# Generated by Django 4.2.6 on 2023-10-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_rename_cartype_carcategory_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcategory',
            name='sum_for_per_km',
            field=models.PositiveIntegerField(default=1500),
        ),
    ]
