# Generated by Django 4.2.7 on 2023-11-13 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driverlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
