# Generated by Django 4.2.6 on 2023-10-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_carcategory_sum_for_per_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
