# Generated by Django 4.2.7 on 2023-11-21 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_alter_driverlocation_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='bearing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='drivers',
            name='car_color',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
