# Generated by Django 4.2.7 on 2023-11-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_driverlocation_bearing_drivers_car_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlocation',
            name='bearing',
        ),
    ]
