# Generated by Django 4.2.7 on 2023-11-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_driverlocation_bearing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlocation',
            name='bearing',
        ),
    ]
