# Generated by Django 4.2.7 on 2023-11-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0011_driverlocation_bearing'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcategory',
            name='for_woman_cost',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='waiting_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
