# Generated by Django 4.2.7 on 2023-11-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0012_carcategory_for_woman_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
    ]
