# Generated by Django 4.2.7 on 2023-12-22 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0014_driverpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverPayment',
        ),
    ]
