# Generated by Django 4.2.7 on 2023-12-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0016_carcategory_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcategory',
            name='driver_min_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
