# Generated by Django 4.2.6 on 2023-11-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser2',
            name='password',
        ),
        migrations.RemoveField(
            model_name='customuser2',
            name='username',
        ),
    ]
