# Generated by Django 4.2.6 on 2023-11-01 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_customuser2_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser2',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser2',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser2',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser2',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser2',
            name='last_name',
        ),
    ]
