# Generated by Django 4.2.6 on 2023-11-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_customuser2_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser2',
            name='is_superuser',
        ),
    ]
