# Generated by Django 4.2.6 on 2023-11-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_customuser2_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser2',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customuser2',
            name='phone',
        ),
    ]
