# Generated by Django 4.2.6 on 2023-11-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_customuser2_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser2',
            name='groups',
        ),
    ]
