# Generated by Django 4.2.6 on 2023-11-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_customuser2_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser2',
            name='user_permissions',
        ),
    ]
