# Generated by Django 4.2.6 on 2023-11-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_customuser_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
