# Generated by Django 4.2.6 on 2023-11-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
