# Generated by Django 4.2.6 on 2023-11-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_driver2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver2',
            options={'verbose_name': 'Driver2'},
        ),
    ]
