# Generated by Django 4.2.7 on 2023-11-10 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_driver2_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver2',
        ),
    ]
